### PR TITLE
feat(notifications): add notifications

### PR DESCRIPTION
**Pull request by xdjeremy**

### CODE REVIEW

**Comment by xdjeremy** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/TimBuilding/wisecare/67?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#69** <a href="https://app.graphite.dev/github/pr/TimBuilding/wisecare/69?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#68** <a href="https://app.graphite.dev/github/pr/TimBuilding/wisecare/68?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#67** <a href="https://app.graphite.dev/github/pr/TimBuilding/wisecare/67?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#65** <a href="https://app.graphite.dev/github/pr/TimBuilding/wisecare/65?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @xdjeremy and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by tamrivera05 — APPROVED** [review]
lgtm :*

**Review by tamrivera05 — CHANGES_REQUESTED** [review]
merge conflict :0

**Comment by xdjeremy** [comment]
### Merge activity

* **Jun 26, 9:04 AM EDT**: [Graphite](https://app.graphite.dev/github/pr/TimBuilding/wisecare/67) rebased this pull request after merging its parent, because this pull request is set to merge when ready.

**Review by tamrivera05 — APPROVED** [review]

**Pull request merged**
